"""Artifact bundle domain types."""

from .manifest import (
    ArtifactRecord,
    ConfigurationRecord,
    ImageDigest,
    RunManifest,
    SourceRevision,
    write_manifest_atomic,
)
from ._adapters.rosbag import (
    BASE_TOPIC_TYPES,
    BASE_TOPICS,
    COMPETITION_TOPIC_TYPES,
    COMPETITION_TOPICS,
    DownwardRangeEvidence,
    FIXED_TOPIC_TYPES,
    FIXED_TOPICS,
    GroundTruthEvidence,
    MissionEventEvidence,
    PayloadEventEvidence,
    PayloadStateEvidence,
    PhysicalBagEvidence,
    RecorderFinalization,
    RosbagRecorder,
    RosbagTopicDiagnostic,
    RosbagValidationResult,
    RosbagValidator,
    ScoreEventEvidence,
)
from ._adapters.docker_logs import (
    DockerLogCapture,
    DockerLogCaptureError,
    DockerLogCaptureResult,
    DockerLogCommandResult,
    DockerLogDiagnostic,
)
from ._adapters.video import (
    VideoDiagnostic,
    VideoFinalization,
    VideoStreamRecorder,
    VideoValidationResult,
    VideoValidator,
)
from .recorder_node import VideoRecorderNode
from .runtime_configuration import (
    RecordingRuntimeConfig,
    resolve_recording_runtime_config,
)
from .session import (
    ArtifactSession,
    FinalizationConflict,
    FinalizationInput,
    FinalizationResult,
)
from .structured_log import StructuredEvent, write_event
from .validation import (
    ValidationResult,
    ValidationStatus,
    read_regular_file_bytes,
    validate_gazebo_state,
    validate_nonempty_regular_file,
    validate_regular_file,
    validate_tree,
)

__all__ = [
    "ArtifactRecord",
    "ArtifactSession",
    "BASE_TOPIC_TYPES",
    "BASE_TOPICS",
    "COMPETITION_TOPIC_TYPES",
    "COMPETITION_TOPICS",
    "ConfigurationRecord",
    "DockerLogCapture",
    "DockerLogCaptureError",
    "DockerLogCaptureResult",
    "DockerLogCommandResult",
    "DockerLogDiagnostic",
    "DownwardRangeEvidence",
    "FinalizationConflict",
    "FinalizationInput",
    "FinalizationResult",
    "FIXED_TOPIC_TYPES",
    "FIXED_TOPICS",
    "GroundTruthEvidence",
    "ImageDigest",
    "PhysicalBagEvidence",
    "MissionEventEvidence",
    "PayloadEventEvidence",
    "PayloadStateEvidence",
    "RunManifest",
    "RecorderFinalization",
    "RecordingRuntimeConfig",
    "RosbagRecorder",
    "RosbagTopicDiagnostic",
    "RosbagValidationResult",
    "RosbagValidator",
    "ScoreEventEvidence",
    "SourceRevision",
    "StructuredEvent",
    "ValidationResult",
    "ValidationStatus",
    "VideoDiagnostic",
    "VideoFinalization",
    "VideoRecorderNode",
    "VideoStreamRecorder",
    "VideoValidationResult",
    "VideoValidator",
    "read_regular_file_bytes",
    "resolve_recording_runtime_config",
    "validate_gazebo_state",
    "validate_nonempty_regular_file",
    "validate_regular_file",
    "validate_tree",
    "write_event",
    "write_manifest_atomic",
]
