services:
  artifacts-runtime:
    devices:
      - /dev/nvidia-caps/nvidia-cap2:/dev/nvidia-caps/nvidia-cap2
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
      SIM_VIDEO_ENCODER: h264_nvenc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  gazebo-runtime:
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,graphics,utility
      __EGL_VENDOR_LIBRARY_FILENAMES: /usr/share/glvnd/egl_vendor.d/10_nvidia.json
    volumes:
      - ./gazebo/config/10_nvidia.json:/usr/share/glvnd/egl_vendor.d/10_nvidia.json:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
