- ros_topic_name: "/gazebo/private/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "GZ_TO_ROS"
  publisher_queue: 1000
  subscriber_queue: 1000
  lazy: false
- ros_topic_name: "/gazebo/private/iris/odometry"
  gz_topic_name: "/gazebo/private/iris/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: "GZ_TO_ROS"
  publisher_queue: 10
  subscriber_queue: 10
  lazy: false
- ros_topic_name: "/world/vertical_descent/model/ground_plane/link/ground_link/sensor/iris_ground_contact/contact"
  gz_topic_name: "/world/vertical_descent/model/ground_plane/link/ground_link/sensor/iris_ground_contact/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: "GZ_TO_ROS"
  publisher_queue: 10
  subscriber_queue: 10
  lazy: false
